# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Chongyao Zhao/ 赵崇遥"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Hangzhou, China"
  employer         : "Zhejiang University"
  uri              : # URL
  email            : "chongyao_zhao1996@qq.com" 
